import { MatchCard } from "@/components/match-card"

const matches = [
  {
    id: "1",
    homeTeam: "Al Hilal",
    awayTeam: "Al Nassr",
    homeTeamArabic: "الهلال",
    awayTeamArabic: "النصر",
    homeScore: 2,
    awayScore: 1,
    status: "live" as const,
    startTime: "15:30",
    competition: "Saudi Pro League",
    competitionArabic: "دوري روشن السعودي",
    homeTeamFlag: "/al-hilal-saudi-football-club-logo.png",
    awayTeamFlag: "/al-nassr-saudi-football-club-logo.png",
    venue: "استاد الملك فهد",
    liveViewers: 45000,
  },
  {
    id: "2",
    homeTeam: "Al Ittihad",
    awayTeam: "Al Ahli",
    homeTeamArabic: "الاتحاد",
    awayTeamArabic: "الأهلي",
    homeScore: 0,
    awayScore: 0,
    status: "live" as const,
    startTime: "20:00",
    competition: "Saudi Pro League",
    competitionArabic: "دوري روشن السعودي",
    homeTeamFlag: "/al-ittihad-saudi-football-club-logo.png",
    awayTeamFlag: "/al-ahli-saudi-football-club-logo.png",
    venue: "استاد الأمير عبدالله الفيصل",
    liveViewers: 32000,
  },
  {
    id: "3",
    homeTeam: "Al Shabab",
    awayTeam: "Al Fateh",
    homeTeamArabic: "الشباب",
    awayTeamArabic: "الفتح",
    homeScore: null,
    awayScore: null,
    status: "upcoming" as const,
    startTime: "18:30",
    competition: "Saudi Pro League",
    competitionArabic: "دوري روشن السعودي",
    homeTeamFlag: "/al-shabab-saudi-football-club-logo.png",
    awayTeamFlag: "/al-fateh-saudi-football-club-logo.png",
    venue: "استاد الأمير فيصل بن فهد",
  },
  {
    id: "4",
    homeTeam: "Al Taawoun",
    awayTeam: "Damac",
    homeTeamArabic: "التعاون",
    awayTeamArabic: "ضمك",
    homeScore: 3,
    awayScore: 0,
    status: "live" as const,
    startTime: "21:00",
    competition: "Saudi Pro League",
    competitionArabic: "دوري روشن السعودي",
    homeTeamFlag: "/al-taawoun-saudi-football-club-logo.png",
    awayTeamFlag: "/damac-saudi-football-club-logo.png",
    venue: "استاد الأمير عبد العزيز بن مساعد",
    liveViewers: 18000,
  },
  {
    id: "5",
    homeTeam: "Al Ettifaq",
    awayTeam: "Al Khaleej",
    homeTeamArabic: "الاتفاق",
    awayTeamArabic: "الخليج",
    homeScore: null,
    awayScore: null,
    status: "upcoming" as const,
    startTime: "19:45",
    competition: "Saudi Pro League",
    competitionArabic: "دوري روشن السعودي",
    homeTeamFlag: "/al-ettifaq-saudi-football-club-logo.png",
    awayTeamFlag: "/al-khaleej-saudi-football-club-logo.png",
    venue: "استاد الأمير محمد بن فهد",
  },
  {
    id: "6",
    homeTeam: "Al Raed",
    awayTeam: "Al Hazem",
    homeTeamArabic: "الرائد",
    awayTeamArabic: "الحزم",
    homeScore: 1,
    awayScore: 2,
    status: "finished" as const,
    startTime: "16:00",
    competition: "Saudi Pro League",
    competitionArabic: "دوري روشن السعودي",
    homeTeamFlag: "/al-raed-saudi-football-club-logo.png",
    awayTeamFlag: "/al-hazem-saudi-football-club-logo.png",
    venue: "استاد الأمير سلطان بن عبد العزيز",
  },
]

export function MatchGrid() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {matches.map((match) => (
        <MatchCard key={match.id} match={match} />
      ))}
    </div>
  )
}
